# Generated by Django 5.1.2 on 2024-11-05 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_eleve', models.CharField(max_length=80)),
                ('total', models.CharField(max_length=50)),
                ('moyenne', models.CharField(max_length=50)),
                ('tri', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('sigle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Classe_exist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fusion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Emploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours1', models.CharField(max_length=80)),
                ('cours2', models.CharField(max_length=80)),
                ('cours3', models.CharField(max_length=80)),
                ('cours4', models.CharField(max_length=80)),
                ('cours5', models.CharField(max_length=80)),
                ('cours6', models.CharField(max_length=80)),
                ('cours7', models.CharField(max_length=80)),
                ('cours8', models.CharField(max_length=80)),
                ('cours9', models.CharField(max_length=80)),
                ('cours10', models.CharField(max_length=80)),
                ('cours11', models.CharField(max_length=80)),
                ('cours12', models.CharField(max_length=80)),
                ('cours13', models.CharField(max_length=80)),
                ('cours14', models.CharField(max_length=80)),
                ('cours15', models.CharField(max_length=80)),
                ('cours16', models.CharField(max_length=80)),
                ('cours17', models.CharField(max_length=80)),
                ('cours18', models.CharField(max_length=80)),
                ('cours19', models.CharField(max_length=80)),
                ('cours20', models.CharField(max_length=80)),
                ('classe', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('sigle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id_eleve', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=80)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100)),
                ('statut', models.CharField(max_length=100)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestschool_app.anneescolaire')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interro1', models.CharField(max_length=50)),
                ('interro2', models.CharField(max_length=50)),
                ('interro3', models.CharField(max_length=50)),
                ('dev1', models.CharField(max_length=50)),
                ('dev2', models.CharField(max_length=50)),
                ('coef', models.CharField(max_length=50)),
                ('tri', models.CharField(max_length=50)),
                ('moy_interro', models.CharField(max_length=50)),
                ('moy_coef', models.CharField(max_length=50)),
                ('eleve_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschool_app.eleve')),
                ('matiere_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschool_app.matiere')),
            ],
        ),
    ]
