# Generated by Django 5.1.2 on 2024-11-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='classe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
