# Generated by Django 5.1.2 on 2024-11-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0002_bulletin_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='classe',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
