# Generated by Django 5.1.2 on 2025-03-15 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0004_remove_emploi_serie_emploi_annee_scolaire_personnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='serie',
        ),
    ]
