# Generated by Django 5.1.2 on 2025-03-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0005_remove_eleve_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='sexe',
        ),
    ]
