# Generated by Django 5.1.2 on 2025-03-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0006_remove_personnel_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='role',
            field=models.CharField(default='Aucun', max_length=100),
        ),
    ]
