# Generated by Django 5.1.2 on 2025-03-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0007_alter_personnel_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personnel',
        ),
    ]
