# Generated by Django 5.1.2 on 2025-03-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0010_alter_personnel_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={'verbose_name': 'Personnel', 'verbose_name_plural': 'Personnel'},
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='password',
        ),
    ]
