# Generated by Django 5.1.2 on 2025-03-15 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0011_alter_personnel_options_remove_personnel_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personnel',
        ),
    ]
