# Generated by Django 5.1.2 on 2025-03-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0013_personnel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={},
        ),
    ]
