# Generated by Django 5.1.2 on 2025-03-15 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0014_alter_personnel_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personnel',
        ),
    ]
