# Generated by Django 5.1.2 on 2025-03-15 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0015_delete_personnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id_personnel', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=80)),
                ('contact', models.CharField(max_length=100)),
                ('role', models.CharField(default='Personnel', max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestschool_app.anneescolaire')),
            ],
        ),
    ]
