# Generated by Django 5.1.2 on 2025-03-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0017_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
