# Generated by Django 5.1.2 on 2025-03-16 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0019_trimestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.CharField(max_length=20)),
                ('classe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschool_app.classe_exist')),
            ],
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
    ]
