# Generated by Django 5.1.2 on 2025-03-16 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0020_tarif_delete_serie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solde_Scolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_actuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschool_app.eleve')),
            ],
        ),
    ]
