# Generated by Django 5.1.2 on 2025-03-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0021_solde_scolarite'),
    ]

    operations = [
        migrations.AddField(
            model_name='solde_scolarite',
            name='montant_total_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='solde_scolarite',
            name='solde',
            field=models.CharField(default='En dette', max_length=20),
        ),
    ]
