# Generated by Django 5.1.2 on 2025-03-16 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0022_solde_scolarite_montant_total_paye_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solde_scolarite',
            old_name='montant_actuel',
            new_name='montant_paye',
        ),
        migrations.RemoveField(
            model_name='solde_scolarite',
            name='montant_total',
        ),
        migrations.RemoveField(
            model_name='solde_scolarite',
            name='montant_total_paye',
        ),
        migrations.RemoveField(
            model_name='solde_scolarite',
            name='solde',
        ),
    ]
