# Generated by Django 5.1.2 on 2025-03-16 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0023_rename_montant_actuel_solde_scolarite_montant_paye_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=80)),
                ('prenom', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('contact', models.DateField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestschool_app.anneescolaire')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschool_app.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Professeur_Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestschool_app.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschool_app.classe_exist')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschool_app.matiere')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschool_app.professeur')),
            ],
        ),
    ]
