# Generated by Django 5.1.2 on 2025-03-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0024_professeur_professeur_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
