# Generated by Django 5.1.2 on 2025-03-16 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0026_alter_professeur_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur_classe',
            name='professeur',
        ),
        migrations.RemoveField(
            model_name='professeur_classe',
            name='annee_scolaire',
        ),
        migrations.RemoveField(
            model_name='professeur_classe',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='professeur_classe',
            name='matiere',
        ),
        migrations.DeleteModel(
            name='Professeur',
        ),
        migrations.DeleteModel(
            name='Professeur_Classe',
        ),
    ]
