# Generated by Django 5.1.2 on 2025-03-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0029_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Choississez un rôle', 'Choississez un rôle'), ('Censeur', 'Censeur'), ('Surveillant', 'Surveillant'), ('Secrétaire', 'Secrétaire'), ('Professeur', 'Professeur'), ('Comptable', 'Comptable')], default='Personnel', max_length=20),
        ),
    ]
