# Generated by Django 5.1.2 on 2025-03-17 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0030_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Choississez un rôle', 'Choississez un rôle'), ('Censeur', 'Censeur'), ('Surveillant', 'Surveillant'), ('Secrétaire', 'Secrétaire'), ('Professeur', 'Professeur'), ('Comptable', 'Comptable'), ('superadmin', 'superadmin')], default='Personnel', max_length=20),
        ),
    ]
