# Generated by Django 5.1.2 on 2025-03-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0031_professeur_user_alter_customuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
