# Generated by Django 5.1.2 on 2025-03-18 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0033_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='solde_scolarite',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestschool_app.anneescolaire'),
        ),
    ]
