# Generated by Django 5.1.2 on 2025-03-20 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0034_solde_scolarite_annee_scolaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cahier_texte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=80)),
                ('matiere', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('contenu', models.CharField(max_length=5000)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestschool_app.anneescolaire')),
                ('id_prof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestschool_app.professeur')),
            ],
        ),
    ]
