# Generated by Django 5.1.2 on 2025-03-20 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0035_cahier_texte'),
    ]

    operations = [
        migrations.AddField(
            model_name='cahier_texte',
            name='trimestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestschool_app.trimestre'),
        ),
    ]
