# Generated by Django 5.1.2 on 2025-03-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0037_coefficient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficient',
            name='classe',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coefficient',
            name='matiere',
            field=models.CharField(max_length=100),
        ),
    ]
