# Generated by Django 5.1.2 on 2025-03-24 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0038_alter_coefficient_classe_alter_coefficient_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='coefficient',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestschool_app.anneescolaire'),
        ),
    ]
