# Generated by Django 5.1.2 on 2025-03-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0039_coefficient_annee_scolaire'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coefficient',
            unique_together={('classe', 'annee_scolaire', 'matiere')},
        ),
    ]
