# Generated by Django 5.1.2 on 2025-03-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0040_alter_coefficient_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personnel',
        ),
    ]
