# Generated by Django 5.1.2 on 2025-03-25 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestschool_app', '0041_delete_personnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultatEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_interro', models.CharField(max_length=100)),
                ('moyenne_generale', models.CharField(max_length=100)),
                ('moyenne_coefficientee', models.CharField(max_length=100)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestschool_app.anneescolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschool_app.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschool_app.matiere')),
                ('trimestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestschool_app.trimestre')),
            ],
        ),
    ]
